/**
 * JECRC Cafeteria - Complete Master Menu Products Dataset
 * Contains all 63 new items across 11 official categories + legacy items.
 */

export const completeCafeteriaMenu = [
  // ==========================================
  // 1. BREAD STATION — SANDWICH (10 items)
  // ==========================================
  {
    name: 'Veg Sandwich',
    slug: 'veg-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Fresh vegetable sandwich packed with crunchy cucumber, tomato slices, butter, and mint chutney.',
    price: 50,
    rating: 4.6,
    reviewsCount: 142,
    preparationTime: '5 min',
    calories: 220,
    tags: ['Sandwich', 'Vegetarian', 'Quick Snack'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Veg Grilled Sandwich',
    slug: 'veg-grilled-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Grilled sandwich filled with fresh vegetables, house herbs, and melted table butter.',
    price: 60,
    rating: 4.8,
    reviewsCount: 230,
    preparationTime: '6 min',
    calories: 260,
    tags: ['Grilled', 'Vegetarian', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Stuffed Potato Grilled Sandwich',
    slug: 'stuffed-potato-grilled-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Crisp grilled sandwich generously stuffed with tempered spiced mashed potatoes and green chilies.',
    price: 60,
    rating: 4.7,
    reviewsCount: 175,
    preparationTime: '6 min',
    calories: 290,
    tags: ['Aloo Sandwich', 'Grilled', 'Desi Favorite'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/stuffed-potato-grilled-sandwich.jpg'
  },
  {
    name: 'Chinese Sandwich',
    slug: 'chinese-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Fusion sandwich stuffed with tangy stir-fried Schezwan noodles and crunchy shredded vegetables.',
    price: 70,
    rating: 4.7,
    reviewsCount: 160,
    preparationTime: '7 min',
    calories: 310,
    tags: ['Fusion', 'Chinese', 'Spicy'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 30,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/chinese-sandwich.jpg'
  },
  {
    name: 'Cheese Grilled Sandwich',
    slug: 'cheese-grilled-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Buttery golden grilled sandwich oozing with melted dairy cheese and herb seasoning.',
    price: 70,
    originalPrice: 85,
    rating: 4.9,
    reviewsCount: 310,
    preparationTime: '6 min',
    calories: 340,
    tags: ['Cheese', 'Grilled', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Bombay Veg Sandwich',
    slug: 'bombay-veg-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Iconic street-style sandwich layered with boiled potatoes, beets, cucumber, onions, and spicy mint chutney.',
    price: 70,
    rating: 4.7,
    reviewsCount: 185,
    preparationTime: '6 min',
    calories: 270,
    tags: ['Street Food', 'Bombay Style', 'Spicy Chutney'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/bombay-veg-sandwich.jpg'
  },
  {
    name: 'Paneer Sandwich',
    slug: 'paneer-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Sandwich filled with seasoned paneer cubes, fresh capsicum, onions, and creamy mint mayonnaise.',
    price: 80,
    rating: 4.8,
    reviewsCount: 220,
    preparationTime: '7 min',
    calories: 330,
    tags: ['Paneer', 'Protein', 'Vegetarian'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/paneer-sandwich.jpg'
  },
  {
    name: 'Tandoori Paneer Sandwich',
    slug: 'tandoori-paneer-sandwich',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: 'Grilled sandwich packed with chargrilled tandoori paneer tikka, spicy relish, and smoked sauce.',
    price: 90,
    originalPrice: 105,
    rating: 4.9,
    reviewsCount: 280,
    preparationTime: '8 min',
    calories: 360,
    tags: ['Tandoori', 'Paneer', 'Chef Special'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Cheese Garlic Bread (3 pcs)',
    slug: 'cheese-garlic-bread-3-pcs',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: '3 pieces of toasted crusty bread topped with garlic infused herb butter and molten melted cheese.',
    price: 60,
    rating: 4.8,
    reviewsCount: 215,
    preparationTime: '6 min',
    calories: 310,
    tags: ['Garlic Bread', 'Cheese', 'Sides'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 30,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/cheese-garlic-bread-3-pcs.jpg'
  },
  {
    name: 'Vegetables Cheese Garlic Bread (3 pcs)',
    slug: 'vegetables-cheese-garlic-bread-3-pcs',
    category: 'Bread Station Sandwich',
    station: 'Bakery & Deli',
    description: '3 pieces of artisanal garlic bread loaded with diced bell peppers, sweet corn, and golden mozzarella.',
    price: 70,
    rating: 4.8,
    reviewsCount: 190,
    preparationTime: '7 min',
    calories: 330,
    tags: ['Garlic Bread', 'Loaded', 'Cheese'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 30,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 2. BURGER (5 items)
  // ==========================================
  {
    name: 'Classic Veg Burger',
    slug: 'classic-veg-burger',
    category: 'Burger',
    station: 'The Campus Grill',
    description: 'Crispy spiced mixed vegetable patty with caramelized onions, tomato, lettuce, and tangy mayo.',
    price: 50,
    rating: 4.7,
    reviewsCount: 240,
    preparationTime: '6 min',
    calories: 320,
    tags: ['Burger', 'Vegetarian', 'Budget Favorite'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Classic Veg Cheese Burger',
    slug: 'classic-veg-cheese-burger',
    category: 'Burger',
    station: 'The Campus Grill',
    description: 'Golden spiced veg patty blanketed with a slice of rich melted cheese and secret house burger relish.',
    price: 60,
    rating: 4.8,
    reviewsCount: 320,
    preparationTime: '6 min',
    calories: 370,
    tags: ['Cheese Burger', 'Vegetarian', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/classic-veg-cheese-burger.jpg'
  },
  {
    name: 'Aachari Paneer Burger',
    slug: 'aachari-paneer-burger',
    category: 'Burger',
    station: 'The Campus Grill',
    description: 'Grilled paneer slab infused with tangy pickling achari spices, crisp onions, and herb dressing.',
    price: 70,
    rating: 4.8,
    reviewsCount: 195,
    preparationTime: '8 min',
    calories: 390,
    tags: ['Paneer Burger', 'Spicy', 'Desi Twist'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Pudina Soya Chaap Burger',
    slug: 'pudina-soya-chaap-burger',
    category: 'Burger',
    station: 'The Campus Grill',
    description: 'Juicy soya chaap marinated in fresh mint and coriander chutney, grilled to perfection in a toasted bun.',
    price: 80,
    rating: 4.7,
    reviewsCount: 155,
    preparationTime: '8 min',
    calories: 360,
    tags: ['Soya Chaap', 'Protein Rich', 'Chef Special'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: true,
    stockCount: 30,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Tandoori Burger',
    slug: 'tandoori-burger',
    category: 'Burger',
    station: 'The Campus Grill',
    description: 'Spiced crispy patty coated in smoky tandoori sauce with shredded lettuce and pickled onions.',
    price: 70,
    rating: 4.8,
    reviewsCount: 210,
    preparationTime: '7 min',
    calories: 380,
    tags: ['Tandoori', 'Spicy', 'Popular'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 3. PIZZA (5 items)
  // ==========================================
  {
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    category: 'Pizza',
    station: 'The Campus Grill',
    description: 'Single cheese pizza topped with fresh tomato basil concasse and molten 100% mozzarella cheese.',
    price: 90,
    rating: 4.8,
    reviewsCount: 260,
    preparationTime: '10 min',
    calories: 480,
    tags: ['Pizza', 'Cheese', 'Classic'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'OTC Pizza',
    slug: 'otc-pizza',
    category: 'Pizza',
    station: 'The Campus Grill',
    description: 'Fresh campus pizza topped with crispy diced onion, green capsicum, and juicy ripe tomatoes.',
    price: 100,
    rating: 4.7,
    reviewsCount: 210,
    preparationTime: '10 min',
    calories: 520,
    tags: ['OTC', 'Pizza', 'Vegetarian'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 30,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Paneer Tikka Pizza',
    slug: 'paneer-tikka-pizza',
    category: 'Pizza',
    station: 'The Campus Grill',
    description: 'Pizza topped with marinated paneer tikka, onion, capsicum, and tomato. Price configurable by Admin.',
    price: 0, // PRICE NOT PROVIDED: Kept configurable by Admin, not orderable until price set
    rating: 4.9,
    reviewsCount: 190,
    preparationTime: '12 min',
    calories: 560,
    tags: ['Paneer Tikka', 'Pizza', 'Admin Price Configurable'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 25,
    isAvailable: false, // Requires admin to configure price before ordering
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Country Feast Pizza',
    slug: 'country-feast-pizza',
    category: 'Pizza',
    station: 'The Campus Grill',
    description: 'Loaded pizza topped with onion, capsicum, tomato, sweet golden corn, and earthy mushrooms.',
    price: 120,
    rating: 4.8,
    reviewsCount: 175,
    preparationTime: '12 min',
    calories: 540,
    tags: ['Country Feast', 'Mushroom', 'Pizza'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 25,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Veggie Supreme Pizza',
    slug: 'veggie-supreme-pizza',
    category: 'Pizza',
    station: 'The Campus Grill',
    description: 'Gourmet pizza with onion, capsicum, tomato, crunchy baby corn, and sliced Spanish black olives.',
    price: 120,
    rating: 4.9,
    reviewsCount: 230,
    preparationTime: '12 min',
    calories: 550,
    tags: ['Veggie Supreme', 'Olives', 'Chef Special'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 30,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 4. PASTA (3 items)
  // ==========================================
  {
    name: 'Pasta Red Sauce',
    slug: 'pasta-red-sauce',
    category: 'Pasta',
    station: 'The Campus Grill',
    description: 'Penne pasta tossed in a robust Italian arrabbiata tomato sauce with herbs, garlic, and sautéed vegetables.',
    price: 80,
    rating: 4.7,
    reviewsCount: 180,
    preparationTime: '8 min',
    calories: 340,
    tags: ['Pasta', 'Arrabbiata', 'Tangy'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/pasta-red-sauce.jpg'
  },
  {
    name: 'Pasta White Sauce',
    slug: 'pasta-white-sauce',
    category: 'Pasta',
    station: 'The Campus Grill',
    description: 'Creamy penne cooked in rich velvety Alfredo béchamel sauce with sweet corn, capsicum, and herbs.',
    price: 90,
    rating: 4.8,
    reviewsCount: 290,
    preparationTime: '8 min',
    calories: 420,
    tags: ['Pasta', 'Alfredo', 'Creamy', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Pasta Pink Sauce',
    slug: 'pasta-pink-sauce',
    category: 'Pasta',
    station: 'The Campus Grill',
    description: 'The best of both worlds: penne smothered in a savory blend of tangy tomato and creamy Alfredo sauce.',
    price: 100,
    rating: 4.9,
    reviewsCount: 245,
    preparationTime: '9 min',
    calories: 390,
    tags: ['Pasta', 'Pink Sauce', 'Chef Special'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 30,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 5. CHIN SE CHINESE (13 items)
  // ==========================================
  {
    name: 'Veg Chowmein',
    slug: 'veg-chowmein',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Desi wok-tossed noodles with shredded cabbage, bell peppers, carrots, spring onions, and dark soy sauce.',
    price: 70,
    rating: 4.7,
    reviewsCount: 310,
    preparationTime: '7 min',
    calories: 320,
    tags: ['Chowmein', 'Noodles', 'Street Chinese'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Veg Hakka Noodles',
    slug: 'veg-hakka-noodles',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Stir-fried noodles with fresh vegetables and Chinese-style seasoning.',
    price: 70,
    rating: 4.8,
    reviewsCount: 275,
    preparationTime: '7 min',
    calories: 310,
    tags: ['Hakka Noodles', 'Chinese', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/veg-hakka-noodles.jpg'
  },
  {
    name: 'Veg Schezwan Noodles',
    slug: 'veg-schezwan-noodles',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Fiery wok-tossed noodles coated in authentic spicy Schezwan chili garlic paste and crisp vegetables.',
    price: 80,
    rating: 4.8,
    reviewsCount: 220,
    preparationTime: '7 min',
    calories: 350,
    tags: ['Schezwan', 'Spicy Noodles', 'Fiery'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/veg-schezwan-noodles.jpg'
  },
  {
    name: 'Veg Fried Rice',
    slug: 'veg-fried-rice',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Aromatic basmati rice stir-fried in a hot wok with finely chopped garden vegetables and soy sauce.',
    price: 70,
    rating: 4.7,
    reviewsCount: 240,
    preparationTime: '6 min',
    calories: 330,
    tags: ['Fried Rice', 'Chinese', 'Classic'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Veg Schezwan Rice',
    slug: 'veg-schezwan-rice',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Zesty fried rice tossed with red Schezwan chili paste, crunchy bell peppers, and scallions.',
    price: 80,
    rating: 4.7,
    reviewsCount: 190,
    preparationTime: '7 min',
    calories: 360,
    tags: ['Schezwan Rice', 'Spicy', 'Popular'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Honey Chilli Potato',
    slug: 'honey-chilli-potato',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Crispy fried potato fingers glazed with sweet chili honey sauce and garnished with toasted sesame seeds.',
    price: 80,
    rating: 4.9,
    reviewsCount: 340,
    preparationTime: '8 min',
    calories: 380,
    tags: ['Honey Chilli', 'Crispy', 'Starters', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/honey-chilli-potato.jpg'
  },
  {
    name: 'Veg Manchurian Dry',
    slug: 'veg-manchurian-dry',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Crispy fried vegetable dumplings tossed dry with ginger, garlic, green chilies, and dark soy glaze.',
    price: 80,
    rating: 4.8,
    reviewsCount: 260,
    preparationTime: '8 min',
    calories: 290,
    tags: ['Manchurian', 'Dry Starter', 'Crispy'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/veg-manchurian-dry.jpg'
  },
  {
    name: 'Veg Manchurian Gravy',
    slug: 'veg-manchurian-gravy',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Soft vegetable balls simmered in a flavorful, thick garlic and coriander Indo-Chinese gravy.',
    price: 90,
    rating: 4.7,
    reviewsCount: 195,
    preparationTime: '9 min',
    calories: 320,
    tags: ['Manchurian', 'Gravy', 'Meals'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Chilli Paneer Dry',
    slug: 'chilli-paneer-dry',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Golden paneer cubes tossed dry with crunchy capsicum, onions, and spicy chili garlic seasoning.',
    price: 100,
    rating: 4.9,
    reviewsCount: 310,
    preparationTime: '8 min',
    calories: 380,
    tags: ['Chilli Paneer', 'Dry Starter', 'Spicy', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Chilli Paneer Gravy',
    slug: 'chilli-paneer-gravy',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: 'Succulent paneer cubes simmered in a luscious hot and sour Indo-Chinese chili sauce with bell peppers.',
    price: 110,
    rating: 4.8,
    reviewsCount: 225,
    preparationTime: '9 min',
    calories: 410,
    tags: ['Chilli Paneer', 'Gravy', 'Popular'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 30,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/chilli-paneer-gravy.jpg'
  },
  {
    name: 'Steam Momos (8 pcs)',
    slug: 'steam-momos-8-pcs',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: '8 pieces of steamed vegetable momos served with spicy red chili chutney and creamy dip.',
    price: 80,
    rating: 4.8,
    reviewsCount: 350,
    preparationTime: '6 min',
    calories: 220,
    tags: ['Momos', 'Steamed', 'Chutney', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Fry Momos with Schezwan Sauce (8 pcs)',
    slug: 'fry-momos-with-schezwan-sauce-8-pcs',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: '8 pieces of crispy deep-fried vegetable dumplings served with fiery homemade Schezwan sauce.',
    price: 90,
    rating: 4.9,
    reviewsCount: 290,
    preparationTime: '7 min',
    calories: 310,
    tags: ['Fried Momos', 'Crispy', 'Schezwan'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Chilli Momos (8 pcs)',
    slug: 'chilli-momos-8-pcs',
    category: 'Chin se Chinese',
    station: 'The Campus Grill',
    description: '8 pieces of crispy fried momos tossed in spicy Indo-Chinese chili garlic sauce with diced onions and capsicum.',
    price: 100,
    rating: 4.9,
    reviewsCount: 270,
    preparationTime: '8 min',
    calories: 340,
    tags: ['Chilli Momos', 'Tossed', 'Spicy', 'Chef Special'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 6. ROLLS (4 items)
  // ==========================================
  {
    name: 'Aloo Roll',
    slug: 'aloo-roll',
    category: 'Rolls',
    station: 'The Campus Grill',
    description: 'Crispy flaky paratha rolled with spiced potato mash, crunchy sliced onions, and tangy mint chutney.',
    price: 50,
    rating: 4.6,
    reviewsCount: 160,
    preparationTime: '6 min',
    calories: 290,
    tags: ['Aloo Roll', 'Kathi Roll', 'Budget Bite'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Veggie Roll',
    slug: 'veggie-roll',
    category: 'Rolls',
    station: 'The Campus Grill',
    description: 'Flaky flatbread wrapped with sautéed mixed bell peppers, shredded cabbage, carrots, and house spiced mayo.',
    price: 60,
    rating: 4.7,
    reviewsCount: 190,
    preparationTime: '6 min',
    calories: 270,
    tags: ['Veg Roll', 'Healthy', 'Fresh'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/veggie-roll.jpg'
  },
  {
    name: 'Paneer Roll',
    slug: 'paneer-roll',
    category: 'Rolls',
    station: 'The Campus Grill',
    description: 'Fresh paratha stuffed with marinated grilled paneer cubes, julienned onions, and savory spiced mint mayo.',
    price: 80,
    rating: 4.8,
    reviewsCount: 310,
    preparationTime: '7 min',
    calories: 360,
    tags: ['Paneer Roll', 'Protein', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/paneer-roll.jpg'
  },
  {
    name: 'Spring Roll',
    slug: 'spring-roll',
    category: 'Rolls',
    station: 'The Campus Grill',
    description: 'Crispy golden fried rolls stuffed with shredded vegetables and glass noodles, served with sweet chili dip.',
    price: 90,
    rating: 4.8,
    reviewsCount: 220,
    preparationTime: '7 min',
    calories: 320,
    tags: ['Spring Roll', 'Crispy', 'Chinese Starter'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/spring-roll.jpg'
  },

  // ==========================================
  // 7. MAGGI DELIGHT (5 items)
  // ==========================================
  {
    name: 'Classic Plain Maggi',
    slug: 'classic-plain-maggi',
    category: 'Maggi Delight',
    station: 'The Campus Grill',
    description: 'The iconic college comfort bowl made with classic 2-minute Maggi masala noodles.',
    price: 40,
    rating: 4.8,
    reviewsCount: 410,
    preparationTime: '4 min',
    calories: 260,
    tags: ['Maggi', 'Hostel Classic', 'Comfort', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 60,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/classic-plain-maggi.jpg'
  },
  {
    name: 'Classic Veg Maggi',
    slug: 'classic-veg-maggi',
    category: 'Maggi Delight',
    station: 'The Campus Grill',
    description: 'Masala noodles cooked with finely chopped green peas, sweet carrots, onions, and mild spices.',
    price: 50,
    rating: 4.8,
    reviewsCount: 330,
    preparationTime: '5 min',
    calories: 290,
    tags: ['Veg Maggi', 'Vegetarian', 'Popular'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/classic-veg-maggi.jpg'
  },
  {
    name: 'Classic Cheese Maggi',
    slug: 'classic-cheese-maggi',
    category: 'Maggi Delight',
    station: 'The Campus Grill',
    description: 'Piping hot masala noodles crowned with a rich blanket of melted dairy cheese and chili flakes.',
    price: 60,
    rating: 4.9,
    reviewsCount: 380,
    preparationTime: '5 min',
    calories: 350,
    tags: ['Cheese Maggi', 'Loaded', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 45,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/classic-cheese-maggi.jpg'
  },
  {
    name: 'Double Masala Maggi',
    slug: 'double-masala-maggi',
    category: 'Maggi Delight',
    station: 'The Campus Grill',
    description: 'For spice lovers: punchy double tastemaker masala infusion cooked to soupy perfection.',
    price: 60,
    rating: 4.8,
    reviewsCount: 290,
    preparationTime: '5 min',
    calories: 280,
    tags: ['Double Masala', 'Spicy', 'Hostel Special'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Extra Masala',
    slug: 'extra-masala',
    category: 'Maggi Delight',
    station: 'The Campus Grill',
    description: 'Extra Maggi tastemaker seasoning packet add-on to intensify your noodle spices.',
    price: 5,
    rating: 4.9,
    reviewsCount: 150,
    preparationTime: '1 min',
    calories: 20,
    tags: ['Add-on', 'Seasoning', 'Maggi'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 100,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 8. FRYDAY (4 items)
  // ==========================================
  {
    name: 'French Fries',
    slug: 'french-fries',
    category: 'Fryday',
    station: 'Fries & Dips Kiosk',
    description: 'Golden, crispy skin-on potato fries lightly salted and served hot with tomato ketchup.',
    price: 50,
    rating: 4.7,
    reviewsCount: 310,
    preparationTime: '4 min',
    calories: 280,
    tags: ['Fries', 'Crispy', 'Snack'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/french-fries.jpg'
  },
  {
    name: 'Masala Fries',
    slug: 'masala-fries',
    category: 'Fryday',
    station: 'Fries & Dips Kiosk',
    description: 'Crispy golden fries tossed in our secret tangy campus chaat masala and herb spice blend.',
    price: 60,
    rating: 4.8,
    reviewsCount: 260,
    preparationTime: '4 min',
    calories: 295,
    tags: ['Masala Fries', 'Spicy', 'Desi'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Peri Peri Fries',
    slug: 'peri-peri-fries',
    category: 'Fryday',
    station: 'Fries & Dips Kiosk',
    description: 'Crunchy potato fries dusted with zesty African bird eye chili peri-peri seasoning.',
    price: 70,
    rating: 4.9,
    reviewsCount: 380,
    preparationTime: '4 min',
    calories: 310,
    tags: ['Peri Peri', 'Spicy Fries', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Cheese Fries',
    slug: 'cheese-fries',
    category: 'Fryday',
    station: 'Fries & Dips Kiosk',
    description: 'Hot crispy french fries smothered with warm, rich molten cheddar cheese sauce and herbs.',
    price: 80,
    rating: 4.9,
    reviewsCount: 340,
    preparationTime: '5 min',
    calories: 370,
    tags: ['Cheese Fries', 'Loaded', 'Indulgent', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 40,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/cheese-fries.jpg'
  },

  // ==========================================
  // 9. ICE WITH MILK SHAKES (7 items)
  // ==========================================
  {
    name: 'Vanilla Shake',
    slug: 'vanilla-shake',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Rich and creamy chilled milkshake made with pure vanilla essence and chilled whole milk.',
    price: 50,
    rating: 4.7,
    reviewsCount: 180,
    preparationTime: '4 min',
    calories: 290,
    tags: ['Milkshake', 'Vanilla', 'Cold Shake'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Strawberry Shake',
    slug: 'strawberry-shake',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Luscious refreshing milkshake prepared with crushed strawberries and cold fresh dairy milk.',
    price: 50,
    rating: 4.7,
    reviewsCount: 165,
    preparationTime: '4 min',
    calories: 280,
    tags: ['Milkshake', 'Strawberry', 'Fruity'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Butterscotch Shake',
    slug: 'butterscotch-shake',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Creamy milkshake infused with sweet butterscotch syrup and crunchy caramelized nougat bits.',
    price: 60,
    rating: 4.8,
    reviewsCount: 220,
    preparationTime: '4 min',
    calories: 320,
    tags: ['Milkshake', 'Butterscotch', 'Crunchy'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 35,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Chocolate Shake',
    slug: 'chocolate-shake',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Thick dark chocolate milkshake crafted with rich cocoa, chocolate drizzle, and fresh cream.',
    price: 60,
    rating: 4.9,
    reviewsCount: 360,
    preparationTime: '4 min',
    calories: 340,
    tags: ['Chocolate Shake', 'Rich Cocoa', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'KitKat Shake',
    slug: 'kitkat-shake',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Decadent chilled shake blended with crispy KitKat chocolate wafer bars and chocolate ganache.',
    price: 70,
    rating: 4.9,
    reviewsCount: 310,
    preparationTime: '5 min',
    calories: 380,
    tags: ['KitKat Shake', 'Dessert', 'Special', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Oreo Shake',
    slug: 'oreo-shake',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Thick cookies & cream shake crushed with original Oreo biscuits and velvety chocolate syrup.',
    price: 60,
    rating: 4.9,
    reviewsCount: 330,
    preparationTime: '4 min',
    calories: 360,
    tags: ['Oreo Shake', 'Cookies & Cream', 'Popular'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Cold Coffee',
    slug: 'cold-coffee',
    category: 'Ice With Milk Shakes',
    station: 'Beverage Bar',
    description: 'Classic frothy campus cold coffee blended with espresso brew, chilled milk, and crushed ice.',
    price: 50,
    rating: 4.9,
    reviewsCount: 450,
    preparationTime: '4 min',
    calories: 220,
    tags: ['Cold Coffee', 'Espresso', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 60,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 10. COFFEE & TEA (4 items)
  // ==========================================
  {
    name: 'Tea',
    slug: 'tea',
    category: 'Coffee & Tea',
    station: 'North Hall Brew Station',
    description: 'Steaming hot daily university milk tea brewed with whole milk, cardamom, and fresh Assam tea leaves.',
    price: 10,
    rating: 4.9,
    reviewsCount: 620,
    preparationTime: '3 min',
    calories: 60,
    tags: ['Chai', 'Tea', 'Campus Daily', 'Bestseller'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 100,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Lemon Ice Tea',
    slug: 'lemon-ice-tea',
    category: 'Coffee & Tea',
    station: 'North Hall Brew Station',
    description: 'Chilled steeped black tea infused with fresh lemon juice, mint sprigs, and crushed crystal ice.',
    price: 30,
    rating: 4.7,
    reviewsCount: 190,
    preparationTime: '3 min',
    calories: 90,
    tags: ['Iced Tea', 'Refreshing', 'Lemon'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 40,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Regular Coffee',
    slug: 'regular-coffee',
    category: 'Coffee & Tea',
    station: 'North Hall Brew Station',
    description: 'Hot aromatic brewed coffee prepared with fresh steamed milk and roasted chicory coffee blend.',
    price: 20,
    rating: 4.8,
    reviewsCount: 290,
    preparationTime: '3 min',
    calories: 80,
    tags: ['Hot Coffee', 'Brewed', 'Daily Kick'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 60,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Black Coffee',
    slug: 'black-coffee',
    category: 'Coffee & Tea',
    station: 'North Hall Brew Station',
    description: 'Steaming cup of pure dark roast coffee brewed Americano-style without milk or sugar.',
    price: 20,
    rating: 4.6,
    reviewsCount: 140,
    preparationTime: '2 min',
    calories: 10,
    tags: ['Black Coffee', 'Zero Calorie', 'Espresso'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // 11. PRODUCTS ON MRP (3 items)
  // ==========================================
  {
    name: 'Cold Drinks',
    slug: 'cold-drinks',
    category: 'Products on MRP',
    station: 'North Hall Brew Station',
    description: 'Assorted chilled canned and bottled sodas (Coke, Sprite, Thums Up, Fanta). Sold at MRP (Configurable by Admin).',
    price: 0, // MRP based - configurable by Admin before ordering
    rating: 4.8,
    reviewsCount: 210,
    preparationTime: '1 min',
    calories: 140,
    tags: ['MRP Item', 'Cold Drink', 'Beverage'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 60,
    isAvailable: false, // Requires admin MRP configuration
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Ice Cream',
    slug: 'ice-cream',
    category: 'Products on MRP',
    station: 'North Hall Brew Station',
    description: 'Assorted branded ice cream cups, cones, and chocobars. Sold at MRP (Configurable by Admin).',
    price: 0, // MRP based - configurable by Admin before ordering
    rating: 4.9,
    reviewsCount: 280,
    preparationTime: '1 min',
    calories: 180,
    tags: ['MRP Item', 'Ice Cream', 'Dessert'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: false, // Requires admin MRP configuration
    image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Lays',
    slug: 'lays',
    category: 'Products on MRP',
    station: 'North Hall Brew Station',
    description: 'Crispy potato chips in assorted flavors (Magic Masala, Classic Salted, Cream & Onion). Sold at MRP (Configurable by Admin).',
    price: 0, // MRP based - configurable by Admin before ordering
    rating: 4.7,
    reviewsCount: 195,
    preparationTime: '1 min',
    calories: 160,
    tags: ['MRP Item', 'Lays', 'Chips', 'Snack'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 80,
    isAvailable: false, // Requires admin MRP configuration
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&q=80&w=600'
  },

  // ==========================================
  // PRESERVED CAMPUS MEALS & SPECIALS
  // ==========================================
  {
    name: 'Special Executive Veg Thali',
    slug: 'special-executive-veg-thali',
    category: 'Meals & Thalis',
    station: 'Campus Thali & Bowls',
    description: 'Complete wholesome lunch meal including Shahi Paneer, Dal Makhani, 3 butter rotis, jeera rice, salad, and gulab jamun.',
    price: 160,
    originalPrice: 190,
    rating: 4.9,
    reviewsCount: 280,
    preparationTime: '12 min',
    calories: 680,
    tags: ['Full Meal', 'Comfort Food', 'Thali'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: true,
    stockCount: 35,
    isAvailable: true,
    image: 'http://localhost:5000/uploads/special-executive-veg-thali.jpg'
  },
  {
    name: 'High-Protein Paneer Rice Bowl',
    slug: 'high-protein-paneer-rice-bowl',
    category: 'Meals & Thalis',
    station: 'Campus Thali & Bowls',
    description: 'Warm jeera basmati rice topped with tawa paneer cubes, tossed edamame beans, yellow lentils dal, and fresh mint chutney.',
    price: 140,
    rating: 4.8,
    reviewsCount: 89,
    preparationTime: '8 min',
    calories: 460,
    tags: ['High Protein', 'Balanced Diet', 'Healthy'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 25,
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCA43inq5WMPCEavtQ-8bodbemfMEDxFvVxK4sCyBiX94bXZCJuUsnbKsZwp19qs4lXxWzym0bE6FuWjnE_r4lr0eNloqCyLqaCEVHjbbjivH9Pu7COAqsufsn9aHuF34zVVTKDhghXICxKeF-JYPWYbXe6xoDWtJpFrynBkFFIIBw7YxW7K7_PLPyMxBkaMU5HBcSFKXJmUl0CVoydJ8hx1P3cY45K8fHLrODzyf9zXwilNQZyxgWO'
  },
  {
    name: 'Rajma Chawal Comfort Bowl',
    slug: 'rajma-chawal-comfort-bowl',
    category: 'Meals & Thalis',
    station: 'Campus Thali & Bowls',
    description: 'Slow-simmered Kashmiri red kidney beans in aromatic onion-tomato masala poured over fragrant steamed basmati rice.',
    price: 90,
    rating: 4.8,
    reviewsCount: 315,
    preparationTime: '5 min',
    calories: 410,
    tags: ['Hostel Classic', 'Comfort Food'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 45,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Fresh Garden Salad Bowl',
    slug: 'fresh-garden-salad-bowl',
    category: 'Healthy & Greens',
    station: 'Green Salad Bar',
    description: 'Fresh organic garden salad bowl with cucumbers, cherry tomatoes, crisp lettuce, olive oil dressing.',
    price: 65,
    rating: 4.5,
    reviewsCount: 95,
    preparationTime: '3 min',
    calories: 120,
    tags: ['Healthy', 'Low Calorie', 'Vegan'],
    isVeg: true,
    isPopular: false,
    isChefSpecial: false,
    stockCount: 25,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600'
  },
  {
    name: 'Crispy South Indian Masala Dosa',
    slug: 'crispy-south-indian-masala-dosa',
    category: 'Breakfast',
    station: 'Bakery & Deli',
    description: 'Golden roasted fermented crepe stuffed with spiced potato bhaji, served with coconut chutney and sambar.',
    price: 70,
    rating: 4.7,
    reviewsCount: 205,
    preparationTime: '6 min',
    calories: 290,
    tags: ['South Indian', 'Breakfast', 'Crispy'],
    isVeg: true,
    isPopular: true,
    isChefSpecial: false,
    stockCount: 50,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600'
  }
];
