/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00714d",
        "surface-dim": "#d2d9f4",
        "surface-tint": "#b42907",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#005236",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#0e009e",
        "primary-fixed": "#ffdad2",
        "tertiary": "#494bd6",
        "on-secondary-fixed": "#002113",
        "on-secondary": "#ffffff",
        "on-surface": "#131b2e",
        "on-tertiary": "#ffffff",
        "surface-variant": "#dae2fd",
        "tertiary-container": "#8487ff",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#eaedff",
        "inverse-primary": "#ffb4a3",
        "error": "#ba1a1a",
        "surface-container-highest": "#dae2fd",
        "on-primary-container": "#5c0e00",
        "on-tertiary-fixed": "#07006c",
        "error-container": "#ffdad6",
        "on-background": "#131b2e",
        "surface-container-high": "#e2e7ff",
        "secondary": "#006c49",
        "surface-container-low": "#f2f3ff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#8b1a00",
        "on-primary-fixed": "#3d0600",
        "secondary-container": "#6cf8bb",
        "secondary-fixed-dim": "#4edea3",
        "on-surface-variant": "#5a413b",
        "inverse-on-surface": "#eef0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "inverse-surface": "#283044",
        "surface": "#faf8ff",
        "background": "#faf8ff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "primary-container": "#ff5e3a",
        "outline-variant": "#e3beb6",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e1e0ff",
        "primary": "#b42907",
        "outline": "#8e7069",
        "primary-fixed-dim": "#ffb4a3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "md": "0.75rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "container-max": "80rem"
      },
      fontFamily: {
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Outfit", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
